# Generated by Django 5.1.7 on 2025-03-17 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_customer_menucategory_rename_first_name_logger_name_and_more'),
    ]

    operations = [
    ]
